print('Enter time')
hours=int(input())
minutes=int(input())
seconds=int(input())
print(f'Time is {hours} hr {minutes} mi {seconds} secs')
print(f'Time in seconds {(hours*3600)+(minutes*60)+seconds}')
